name: custom_mono_repo

packages:
  - utilities/**
  - zathura/**
  - '*'

scripts:
  analyze: melos exec -- flutter analyze
  format: melos exec -- flutter format .
  get: melos exec -- flutter pub get
  upgrade: melos exec -- flutter pub upgrade --major-versions
  unittest: 
    run: melos exec -- flutter test
    select-package:
      dir-exists:
        - test
      scope: "*interface*"